# Generated by Django 4.1.7 on 2023-03-28 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre/s')),
                ('last_name', models.CharField(max_length=80, verbose_name='Apellido/s')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('last_login', models.DateTimeField(null=True, verbose_name='Último Login')),
                ('created_at', models.DateTimeField(auto_now_add=True, max_length=0, verbose_name='Creado')),
                ('is_superuser', models.BooleanField(default=0, verbose_name='Estado Super Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_audio', models.CharField(max_length=150, verbose_name='Nombre Audio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
