# Generated by Django 4.1.7 on 2023-04-03 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 3, 21, 15, 34, 859965, tzinfo=datetime.timezone.utc), max_length=0, verbose_name='Creado'),
            preserve_default=False,
        ),
    ]
