# Generated by Django 4.1.7 on 2023-04-17 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
